### ISSUE TITLE
Minecraft 1.12.2 work not with the new Music-Player-Forge-1.12.2-2.1.1.239 Update 

### ISSUE THREAD

**Issue by Titoo8899** [MC-U-Team/Music-Player#1022]
### Bug description and reproduction steps

I have download the newest Update of Music Player Mod and U-Team-Core Mod and only the Core Mod load the Music Player Mod load not. I hope you can fix it. I have no other Mods in the Mod Folder and the Game Crash not is only a load Problem (detection problem) of the Music Player Mod. I hope you can fix it.

MC Mod Versions
- Music-Player-Forge-1.12.2-2.1.1.239
- U-Team-Core-Forge-1.12.2-2.2.5.292

1. Put the 2 Mods in the Mod Folder
2. Start Minecraft
3. Start the Forge Application in the Minecraft Hub
4. Look ingame in a world or in the Main Menü in the Mod area and you see only the U-Team-Core Mod but the Music Player Mod was miss and Minecraft have not load this.

### Log files and Screenshots

![2024-04-29_19 54 11](https://github.com/MC-U-Team/Music-Player/assets/42325138/b17fbe02-ddf1-4b06-84fd-2bfd746cbf29)
![2024-04-29_19 54 19](https://github.com/MC-U-Team/Music-Player/assets/42325138/9fa8619f-ee25-4b3d-85a7-15ec529fa9d8)

### Used minecraft version

None

### Used forge or fabric version

1.12.2 - 14.23.5.2860

### Used mod version

Music-Player-Forge-1.12.2-2.1.1.239

**Comment by HyCraftHD** [comment]
Many thanks for the report.
I have found the bug and will push an update soon. At the moment it's only on Modrinth anyway, as Curseforge is still manually checking the files forever.

Interestingly, the game does not crash in version 1.12.2, but only ignores the mod file. The same error occurs in version 1.14.4, but the game crashes. The reason is that ASM cannot read the module-info.class. But 1.15.2 ASM is new enough to be able to do this.

**Comment by HyCraftHD** [comment]
Should be fixed in this version: https://modrinth.com/mod/music-player/version/2.1.1.249
