### ISSUE TITLE
1.17.1?

### ISSUE THREAD

**Issue by greymesa** [MC-U-Team/Music-Player#272]

**Comment by prototype464** [comment]
There has not been any updates or notices on a release for this version for months, HycraftHD says there is no ETA, but people would genuinely appreciate some kind of notion for an update, given that this is the only widely-known mod of its kind.

Please throw us a bone? It may quell the amount of people asking, or opening GitHub issues like this (which may not be the best way of doing it)

If anything, I'm probably just going to try forking and updating it myself because I really relied on this mod a lot.

Edit: I just realized Minecraft 1.17.1 uses Java 16, and I don't know if Music Player has that integrated yet - plus I do not know how to program, so even something as simple as compiling this into a useable mod jar file is not something I'd easily figure out ;_;

Edit2: I also just remembered I'm using Fabric lol, although I think this might be something cool to use as an example:
https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-fabric-edition

Dynamic Surroundings was stuck in development for a while, but now it's working for 1.17.1 as a Fabric version, which is much more lightweight and apparently a lot easier to create and maintain.

"Will will there be updates to the Forge version of Dynamic Surroundings?  At the moment I am not sure. I have limited time, so I need to be a bit picky about what I do. I have found that writing Fabric mods is much easier than on Forge, though it could just be the nature of what my mod does. Take this as a biased assessment."

In the case of Music Player, while I have the chance here, I'd like to mention that a Fabric version may be best given how little time is available for HycraftHD's development and it would be a lot easier to maintain + this kind of mod is the perfect candidate for a Fabric mod

**Comment by HyCraftHD** [comment]
1.18.1 forge is published on curseforge now. Get it here https://www.curseforge.com/minecraft/mc-mods/music-player/files
