### ISSUE TITLE
[1.8.9] Cannot play some songs but can play other ones.

### ISSUE THREAD

**Issue by ElliotHulse** [MC-U-Team/Music-Player#44]
**Describe the bug**
I cannot play some of the songs I want and I can play others. The songs I cannot play are just skipped through in the playlist. Also while skipping through the unplayable songs they turn red. I have also uploaded a video on Youtube regarding this issue. This is the link. https://youtu.be/1YqUn0Fod3k

**To Reproduce**
1. Go to the mod menu.
2. Press play on the playlist.

**Expected behaviour**
Play all the songs in the playlist

**Screenshots**

**Versions**
- Music_Player 1.8.9-2.0.3.55
- Minecraft 1.8.9
- Forge 11.15.1.2318-1.8.9
- UTeamCore 1.3.0.63

**No crash occurring

**Comment by HyCraftHD** [comment]
1.8.9 ist kinda unsupported but I'll update it eventually. Don't expect any time.

**Comment by ElliotHulse** [comment]
I guessed so, just wanted to double-check. Still thank you for responding. Have a good day!

**Comment by Wavebuilder14UDC** [comment]
Just would like to say that I'm on 1.12.2 and this bug is happening to me as well. I have 26 songs in my playlist, some of them up to 30 minutes long.. The day I added them to the playlist or more specifically when they were the only songs in the playlist everything worked fine.. but after adding more songs, now the same songs that worked previously are just skipped until a song that can be played enters the queue.

**Comment by HyCraftHD** [comment]
Update to the latest version. That happens because youtube and other providers change their format and therefore I need to update the lavaplayer version or wait till its fixed there

**Comment by Wavebuilder14UDC** [comment]
Just to clarify: latest version of Minecraft or latest version of the mod?

**Comment by HyCraftHD** [comment]
Latest mod version.
![grafik](https://user-images.githubusercontent.com/7681220/79109199-2778d800-7d78-11ea-9c8e-5a1dabdd370d.png)

**Comment by HyCraftHD** [comment]
Is now fixed in the 1.8 builds
