### ISSUE TITLE
Unable to grab libraries correctly.

### ISSUE THREAD

**Issue by Tlopfest** [MC-U-Team/Music-Player#6]
While attempting to load the libraries for the mod, it seems to only be targeting the java.exe file. However, Linux OS does not use java.exe. It just uses java. No extension. Is there any way to let gradle realize which OS it is in and correctly access the java file?

[latest.log](https://github.com/MC-U-Team/Music-Player/files/3160191/latest.log)

**Comment by HyCraftHD** [comment]
This is a bug in an older version. Try the newest version on https://minecraft.curseforge.com/projects/music-player/files (Music-Player-1.12.2-1.2.0.5)

In this version all libaries are shipped in the jar (So no need for gradle downloads)

If you are using this with an older minecraft version i might try to fix it, but this will take some time because i need to build every version on its own.

**Comment by HyCraftHD** [comment]
Okay this was faster than expected.
The gradle executor should now find the right java executable depending on the operating system.
https://github.com/MC-U-Team/Music-Player/commit/579820bf2348436eced118bded6812aeb9c8102b

When curseforge approves it you can download it here: https://minecraft.curseforge.com/projects/music-player/files
